development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: "redis://:p68421adb96a39dce77f5dfdae1606b5d684c3db498f4a2adc0d2bc16c87c5b54@ec2-44-206-23-135.compute-1.amazonaws.com:22429"
  channel_prefix: lacks_production
